### PR TITLE
Correct placement of error messages when using Select2

### PR DESCRIPTION
**Pull request by seanthepottingshed**
For when this package is being used in conjunction with the Select2 jQuery library:

http://select2.github.io/

### CODE REVIEW

**Comment by torrentalle** [comment]
Leave this pull request open, I will merge it in next release

**Comment by JoeriAben** [comment]
What is the estimated time for the merge to happen?

**Comment by marcelogarbin** [comment]
Any news?

**Comment by modestguy** [comment]
@marcelogarbin https://github.com/seanthepottingshed/laravel-jsvalidation/blob/41d1c7664d30a9782ea597194e90b8eb848c7502/resources/views/bootstrap.php

**Comment by a-komarev** [comment]
`bootstrap.php` file is publishable and you are free to change it to fit your project requirements.

**Comment by mxfragz** [comment]
@antonkomarev 

I've edited the bootstrap.php, but doesn't that mean that if I ever update or install the project on another computer, my changes will be overwritten? How can I prevent that?

**Comment by bytestream** [comment]
Sorry closing this. You can override the bootstrap file to meet your requirements.

**Pull request closed without merging**
