### PR TITLE
Add Travis CI tests for Laravel 5.4

### PR DESCRIPTION
**Pull request by a-komarev**
- Add Travis CI tests for Laravel 5.4
- Cleanup test composers contents

### CODE REVIEW

**Comment by akkhan20** [comment]
build fail :(

**Comment by a-komarev** [comment]
It's not completely failing. Laravel 5.4 is working. The main goal of this PR is add automated Laravel 5.4 testing. Return support of Laravel 5.3 and lower will be the next step.

**Comment by akkhan20** [comment]
so the main package is now 5.4 compatible? or is it dev-master that supports 5.4

**Comment by a-komarev** [comment]
https://travis-ci.org/proengsoft/laravel-jsvalidation/jobs/251770946

**Comment by a-komarev** [comment]
Only `dev-master` is supporting Laravel 5.4. And it's not supporting any older Laravel versions.

**Comment by akkhan20** [comment]
let me update and check i pray the array validation has been fixed magically

**Comment by a-komarev** [comment]
@akkhan20 sure! I've just finished this PR. Waiting that all Travis jobs comple and ready for merge.

**Comment by akkhan20** [comment]
the package is not generating the js rule for var.* => 'min:5|max:15' where as when i dug in previously reported issue i see the package owner stating that this issue has been fixed and functional in latest package

**Comment by akkhan20** [comment]
the rule in laravel is like:
`'description'   =>  'required|min:30:max:500',
'tasks.*'   =>  'min:10|max:65500'`

but the rule generated in js is:
`rules: {"description":{"laravelValidation":[["Required",[],"Description is required",true],["Min",["30:max:500"],"Description too short(minimum 30 characters)",false]]}}        })`

**Comment by a-komarev** [comment]
@akkhan20 You'd better place it in proper issue: #253 
This one related to Travis tests.

**Pull request merged**
