### PR TITLE
Issue 44

### PR DESCRIPTION
**Pull request by torrentalle**
Route Model Binding Form Request Validation Error #44

### CODE REVIEW

**Comment by seanthepottingshed** [comment]
Thank you so much for all your hard work as regards the integrating of the FormRequest. Would you be able to provide an example of Unique validation performed for creating and editing a record please?

( In particular I'm interested in the implementation of the UpdateMenuRequest example I mentioned previously. )

I'm a little confused as to how to handle this via my routes...

**Comment by torrentalle** [comment]
Example using JsValidation with [eloquent-sluggable](https://github.com/cviebrock/eloquent-sluggable)

**RouteServiceProvider.php**

```php
<?php namespace App\Providers;

use App\Menu;
use Illuminate\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider {

	protected $namespace = 'App\Http\Controllers';

	public function boot(Router $router)
	{
		$router->bind('menu', function($slug)
		{
			return Menu::findBySlugOrId($slug);

		});
		parent::boot($router);
	}

	public function map(Router $router)
	{
		$router->group(['namespace' => $this->namespace], function($router)
		{
			require app_path('Http/routes.php');
		});
	}

}
```

**routes.php**
```php
Route::get('menu/{menu?}','MenuController@editMenu');
Route::post('menu/{menu?}','MenuController@postMenu');
```

**UpdateMenuRequest.php**
```php
<?php namespace App\Http\Requests;

class UpdateMenuRequest extends Request {

    public function rules()
    {
        $currentIdRule = is_null($this->route('menu'))? '' : ','.$this->route('menu')->id;
        return array(
            'title' => 'required|unique:menus,title'.$currentIdRule,
            'url'  => 'required|url'
        );
    }
}
```
**MenuController.php**
```php
<?php namespace App\Http\Controllers;

use App\Http\Requests\UpdateMenuRequest;
use App\Menu;
use Illuminate\Http\Request;

class MenuController extends Controller {

    public function editMenu(Menu $menu)
    {
        return view('updatemenu', compact('menu'));

    }

    public function postMenu(Request $request, UpdateMenuRequest $form, Menu $menu) {

		// Save the entry
		$data = $request->only('title', 'url');
      	$menu->fill($data);
        $menu->save();

		return redirect("/menu/{$menu->getSlug()}");
    }

}
```
**updatemenu.blade.php**
```html
@extends('app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Javascrit Validation</div>
                    <div class="panel-body">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" role="form" method="POST" action="/menu/{{$menu->slug}}" id="form-menu">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                            <div class="form-group">
                                <label class="col-md-4 control-label">Title</label>
                                <div class="col-md-6">
                                    <input class="form-control" name="title" value="{{$menu->title}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label">URL</label>
                                <div class="col-md-6">
                                    <input class="form-control" name="url"  value="{{$menu->url}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary" style="margin-right: 15px;">
                                        Submit
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {!! JsValidator::formRequest('App\Http\Requests\UpdateMenuRequest') !!}

@endsection
```

**Comment by seanthepottingshed** [comment]
That looks the business, will have a fettle at work tomorrow ;)

**Comment by seanthepottingshed** [comment]
I've tried the above but the unique parameter doesn't work when updating. My routes are as follows:

```
Route::resource('menus', 'MenusController', ['except' => 'show']);
Route::post('menus/{menuSlug?}', 'MenusController@store');
```

Menus controller:

```
public function update(Menu $menu, UpdateMenuRequest $request)
{
	$data = $request->all() + ['slug' => Str::slug($request['title'])];

	$menu->update($data);

	return redirect('admin/menus');
}
```

The AJAX post is made however the backend validates this as an error if no change is made to the title, whereas it should allow the submission of the same title and only check to see if it's unique when the value has checked.

**Pull request merged**
