### PR TITLE
Laravel 7

### PR DESCRIPTION
**Pull request by bytestream**
Updated test suite for Laravel 7

This drops support for Laravel 5.4 and 5.5. Some time ago someone added a dependency on symfony/http-foundation in JavaScript/MessageParser.php and the constructor arguments changed in v4.1 when they deprecated the `$size` argument.

### CODE REVIEW

**Comment by hamidafghan** [comment]
Anyone can update the documentation, please.

**Comment by bytestream** [comment]
What needs changing @hamidafghan ?

**Comment by hamidafghan** [comment]
The installation guide for Laravel 7.x.

**Comment by bytestream** [comment]
Laravel 7.x requires `^3.0` of this package. The rest of the installation is the same as before. 

You're welcome to edit the wiki pages.

**Pull request merged**
