### PR TITLE
Improved form requests

### PR DESCRIPTION
**Pull request by bytestream**
### Usage

Change your form request to `extends \Proengsoft\JsValidation\Remote\FormRequest`. Then use `\JsValidator::formRequest(MyRequest::class)`

### Description

This solves several issues with client side validation of form requests:
* currently we initialise a "fake" form request in order to generate the rules. The premature nature of this means rules may not be accurate i.e. if you use `$this->some_input_data` - this data will only be available in a real request.
* moves validation back to Laravel rather than using client side rules. This solves several issues:
    * https://github.com/proengsoft/laravel-jsvalidation/issues/504 - issue described above
    * https://github.com/proengsoft/laravel-jsvalidation/issues/465 
    * https://github.com/proengsoft/laravel-jsvalidation/issues/476 - no need to worry about missing validation rules, nothing happens client side anymore

### How does it work

A single AJAX request validation rule is registered against a dummy `input[type=hidden]` field which is generated on-the-fly.

When you submit the form an AJAX fires which does the form request validation. The error response is then mapped back to the input fields in the DOM and errors displayed using `jquery-validation` methods.

### Potential pitfalls

Previously inputs were validated as you typed. Now they're only validated when you submit the form. If you change an invalid input, it's no longer immediately validated so the error will go away. When you submit the form, if it's still invalid the error will be reshown.

### CODE REVIEW

**Comment by yangm97** [comment]
> Previously inputs were validated as you typed. Now they're only validated when you submit the form.

What about validating inputs when they lose focus?

**Comment by bytestream** [comment]
> > Previously inputs were validated as you typed. Now they're only validated when you submit the form.
> 
> What about validating inputs when they lose focus?

Could do that but it will fire a lot of AJAX requests in the background

**Comment by yangm97** [comment]
> > > Previously inputs were validated as you typed. Now they're only validated when you submit the form.
> > 
> > 
> > What about validating inputs when they lose focus?
> 
> Could do that but it will fire a lot of AJAX requests in the background

It shouldn't? In theory there should only be a request when the user switches from one input to the next, which doesn't happen very often.

However, looking at this again, it would seem like the last input would only be validated when clicking the submit, since most users don't change the focus of the last input and instead go straight to the submit button. 
So it's very likely the lose focus event would happen almost at the same time as the submit click event, thus sending two validation requests simultaneously... not sure if this is enough of an issue or not.

**Comment by bytestream** [comment]
The validation is registered against a hidden field that's generated dynamically on page load. Validation will only occur on form submission, as there are no "real" (`noop`) validation rules registered against the  expected fields

**Comment by MGParisi** [comment]
I'm missing something.  Maybe I got the wrong version?  This has now just caused the entire thing to stop working.  It now refreshes the page and ignores the entire check and falls back on Server side.  Also, the form now has a novalidate element.

**Pull request merged**
