### PR TITLE
Configure Remote Validations

### PR DESCRIPTION
**Pull request by samuelfa**
Hi!

I added control to allow use or not Remote Validation. Currently I don't want use because I have my project created with this checks at POST process then I don't interested to create per each Remote Validation Rule a request to check it.

Thank you
Samuel

### CODE REVIEW

**Comment by samuelfa** [comment]
I updated the code to support i18n in the system. To keep the use of "$.validator.format" I need to strip the code inside of validator.js outside to this file and added before to add the JS with language selected.

To selected the correct language on my template I put this:

```html
    <script src="{{ asset('vendor/jsvalidation/js/validator.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/jsvalidation/js/i18n/'.App::getLocale().'.js') }}" type="text/javascript"></script>
```

I'm using the code of Laravel to known witch language it's set at application.

After that I'm including normal JS:

```html
<script src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}" type="text/javascript"></script>
```

**Comment by samuelfa** [comment]
Finally, It's important notice that I used Google Translate to set up the language on German, French and Italian.

**Comment by torrentalle** [comment]
Hi @samuelfa localization is currently supported using Laravel localization system, isn't nedded to do with Javascript. 
By default messages are translated automatically to the Laravel configured language. If you are using custom messages you can use the medthod described in [Laravel Docunentation](http://laravel.com/docs/5.1/validation#custom-error-messages)

**Comment by torrentalle** [comment]
In the other hand, allow remote validations to be optional is a nice feature, thanks

**Comment by torrentalle** [comment]
Can you patch your branch to remove the localization related commits?
Then I will update the unit tests to pass the checks

Gracias

**Comment by samuelfa** [comment]
Hi torrentalle!

About the topic of location It's true the point that You had described but currently the script jsvalidation.js at line 326 has a collection of strings declared on the internal property called messages in English that is using to notice errors when a email is invalid for example. 

This is the reason that I needed to add a collection of text per different languages. Other notices of errors has been provided with Laravel declared at folder resources/lang/[language set]/validation.php

If We don't interested to mixed translations on Javascript then, We must to remove this translations and read from Laravel as the same way that it's doing for others notices.

**Comment by torrentalle** [comment]
I see what you're talking.... it's a bug. 

The validations are written using [JQuery Validation Plugin](http://jqueryvalidation.org/), that is merged with Laravel validations into `public/js/jsvalidation.js` file. In some cases the field is validated using validations provided by JQuery Validation Plugin instead of the provided by JsValidation (`resources/js/validations.js`). In this cases the message is processed by JQuery Validation Plugin and is not translated.

According to [JQuery Validation Plugin documentation](http://jqueryvalidation.org/rules/)
> There are several ways to specify validation rules.
   - Validation methods with parameters can be specified as attributes (recommended)
   - Validation methods without parameters can be specified as classes on the element
   - Both can be specified using the rules-option of the validate()-method
   - Both rules and messages can be specified using data attributes, using data-msg (a generic, not-method specific message), data-msg-[method] and data-rule-[method].

This can cause unexpected messages or validations (ex issue #27). I think that the most safety solution should be **disable this features from JQuery Validation Plugin**:
  - Validation methods with parameters can be specified as attributes
  - Validation methods without parameters can be specified as classes on the element
  - Both rules and messages can be specified using data attributes, using data-msg (a generic, not-method specific message), data-msg-[method] and data-rule-[method].

One of roadmap point is to remove JQuery Validation Plugin dependency, to reduce the size of Javascript assets. All new Javascript code is writed in this direction.

**Comment by torrentalle** [comment]
I fix this issue in `dev-master`branch. Can you test if works as expected?

**Comment by samuelfa** [comment]
Hi again!

I remove all files of i18n and merge the master branch with my forked project.

I check the behavior of JSValidation and works correctly getting the translation from Laravel.

Thanks

**Comment by torrentalle** [comment]
Your contribution is merged i master. I will be release it in the thex release.
I have changed the config name to `enable_remote_validation`, I think is more clear.

**Comment by torrentalle** [comment]
I will replace the variable with `disable_remote_validation` to avoid break existing installations

**Comment by tim-peterson** [comment]
`disable_remote_validation` doesn't work with more common scenarios like remote validation of a unique email. [The default Laravel 5 registration](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/AuthController.php#L57) can't use JSValidation because there are many fields in a registration field, e.g., `name` and yet the POST only validates the `email` so the validation fails with the following message:

```
ErrorException in AuthController.php line 60:
Undefined index: name
```

**Comment by torrentalle** [comment]
I can't reproduce your issue. When `disable_remote_validation`is set to `true` remote validations shlound't be triggered.
Cany you post your Javascript generated *rules* ?

**Pull request merged**
