### PR TITLE
Partially fixes #229

### LINKED ISSUE #229: Array validation is misapplied
**TLDR** is checkout this demo `<form>` and use case explanation: https://github.com/derekmd/laravel-jsvalidation-array-rule-demo (main file: https://github.com/derekmd/laravel-jsvalidation-array-rule-demo/blob/master/resources/views/form.blade.php#L23)

There are issues with:

* validation rule `array` as it applies to PHP forms
* wildcard `*` matching of PHP form array keys in the DOM

```php
[
    'first_name' => 'array',
    'first_name.*' => 'required|string|min:2',
];
```

When typing into form elements `<input name="first_name[]">` or`<input name="first_name[some_key]">`, validation rule `array` is applied to that typed value instead of the `required`, `string`, and `min` validation rules.

I confirmed this bug has existed since 1.4.2 but I haven't tried versions before that.

This is likely a duplicate of https://github.com/proengsoft/laravel-jsvalidation/issues/221 but they didn't give much about what debugging steps were attempted.

### PR DESCRIPTION
**Pull request by bytestream**
See second issue described here https://github.com/proengsoft/laravel-jsvalidation/issues/229#issuecomment-374589085

Assuming you're happy with this I would appreciate if I can also copy to v1. Please could you create a v1 branch or copy this yourself?

### CODE REVIEW

**Comment by a-komarev** [comment]
I've created [branch v1](https://github.com/proengsoft/laravel-jsvalidation/tree/v1). Sorry I don't have enough time to test it now. Could anybody confirm that this fix solves an issue?

**Comment by bytestream** [comment]
@a-komarev done

**Comment by a-komarev** [comment]
@bytestream great, thanks! Have you tested it? Because I've tested only 1st part of your solution and merged it because its working well.

**Comment by bytestream** [comment]
@a-komarev it resolved the issue I was having but I haven't tested it extensively

**Comment by a-komarev** [comment]
I'll merge it to allow you, @derekmd and other people who has same issue to test it on `dev-master`, and if there will be no issues - I will make a release.

**Pull request merged**
