### PR TITLE
Adding window load for JavaScript defer

### PR DESCRIPTION
**Pull request by vrkansagara**
@salbertson Ping

### CODE REVIEW

**Comment by bytestream** [comment]
Not sure this is necessary? You could submit a form while images are still loading in the background

**Comment by vrkansagara** [comment]
@bytestream  I agree with you, but the base idea behind this PR is to completely load third party input as well and make sure that dom is completely loaded to act with js validation!

**Comment by vrkansagara** [comment]
@bytestream There is another use case of this change to use `defer` javascript.

**Comment by bytestream** [comment]
I think I would advise to just override the default view to meet your own needs.

**Comment by vrkansagara** [comment]
@bytestream  This PR should re-open for more vote.

**Pull request closed without merging**
