### PR TITLE
Support Laravel 5.8

### PR DESCRIPTION
**Pull request by sangnguyenplus**

### CODE REVIEW

**Comment by Braunson** [comment]
Can we get this merged @proengsoft?

**Comment by mgkprod** [comment]
👍

**Comment by OmathiasO** [comment]
Hey, do you guys know what went wrong in the StyleCI Check?
It states that the analysis was misconfigured. How can we configure it correctly so that we can build version 2.4?

**Comment by gwleuverink** [comment]
@torrentalle @proengsoft Any chance you can take a look at this PR?

**Comment by gwleuverink** [comment]
For the time being, anyone who'd like to install v2.4.0 add the following to your composer.json:

**Comment by OmathiasO** [comment]
thank you, @drjoju !
now we only need a new release 2.4.0 and we are done here 👍

**Pull request merged**
