### PR TITLE
Rebuild static scripts

### LINKED ISSUE #239: [JS] JPEG mime-type check in image rule
I'm trying to upload an image with jpeg extension, using the image rule.
If i disable the client validation, the image validates correctly, but when using the javascript validation, the client side validation fails.

When I add jpeg in this line https://github.com/proengsoft/laravel-jsvalidation/blob/master/public/js/jsvalidation.js#L3991  in my local copy it seems to be fixed.

### PR DESCRIPTION
**Pull request by a-komarev**
- Add bower to NPM dependencies
- Update javascript libraries
- Rebuild static scripts
- Fix #239

### CODE REVIEW

**Comment by a-komarev** [comment]
There are changes in `php-date-formatter` javascript library. This requires to be checked before release.

**Comment by a-komarev** [comment]
Calling collaborators: @simonigd @akkhan20 @bastman69 @asurace

**Comment by akkhan20** [comment]
the owner of the package `php-date-formatter` says the package follows SemVer standards

**Comment by a-komarev** [comment]
Thank you, @akkhan20! I'll merge it then, after scrutinizer finishes it's job.

**Pull request merged**
