### PR TITLE
Updated test suite

### PR DESCRIPTION
**Pull request by bytestream**

### CODE REVIEW

**Comment by bytestream** [comment]
@antonkomarev I intend to push several fixes which I have had on my fork. My fork has been used in production for 12months+ by several hundred people. Hoping you're willing to merge them so I can close my fork.

**Comment by antonkomarev** [comment]
@bytestream core maintainer has returned recently. Pining @torrentalle for reviewing this PR.

**Comment by bytestream** [comment]
Any updates on this @torrentalle @antonkomarev

**Comment by bytestream** [comment]
@antonkomarev don't think he's back. What's it going to take to see done movement on this? I'm happy to help with this repo, I've been using it and submitting PRs for a long time.

**Comment by antonkomarev** [comment]
@bytestream I've received email from him 30.01.2019 with words like "now I can retake this project contribute back again". I don't really know the exact situation. I'm just a user of this library, so I can't give you rights to merge PRs and don't have enough time to maintain this project because not using it in any of my projects for now.

**Pull request merged**
